In [1]:
from sklearn.tree import DecisionTreeClassifier

In [2]:
x = [[1, 1], [2, 2]]

In [3]:
x

[[1, 1], [2, 2]]

In [4]:
y = [0, 1]

In [5]:
y

[0, 1]

In [6]:
clf = DecisionTreeClassifier()

In [7]:
clf2 = clf.fit(x, y)

In [8]:
clf2.predict([[3, 3]])

array([1])

In [9]:
clf2.predict_proba([[3, 3]])

array([[0., 1.]])

In [10]:
from sklearn import datasets, metrics
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.externals.six import StringIO
from pandas import DataFrame
import numpy as np

C:\Users\alee8\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [11]:
from sklearn.model_selection import train_test_split

In [12]:
dataset = datasets.load_iris()

In [13]:
dataset_head = dataset.data[:10,]

In [14]:
dataset_head

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [15]:
DataFrame(dataset_head, columns=dataset.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [16]:
X_train, X_test, y_train, y_test = train_test_split(dataset.data, dataset.target, test_size=0.5, random_state=1)

In [17]:
model = DecisionTreeClassifier()

In [18]:
fit = model.fit(X_train, y_train)

In [19]:
out = StringIO()

In [20]:
export_graphviz(fit, out_file=out, feature_names=dataset.feature_names, class_names=dataset.target_names, filled=True, rounded=True)

In [21]:
print(out.getvalue())

digraph Tree {
node [shape=box, style="filled, rounded", color="black", fontname=helvetica] ;
edge [fontname=helvetica] ;
0 [label="petal width (cm) <= 0.8\ngini = 0.666\nsamples = 75\nvalue = [26, 26, 23]\nclass = setosa", fillcolor="#ffffff"] ;
1 [label="gini = 0.0\nsamples = 26\nvalue = [26, 0, 0]\nclass = setosa", fillcolor="#e58139"] ;
0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;
2 [label="petal length (cm) <= 5.0\ngini = 0.498\nsamples = 49\nvalue = [0, 26, 23]\nclass = versicolor", fillcolor="#e8fcf0"] ;
0 -> 2 [labeldistance=2.5, labelangle=-45, headlabel="False"] ;
3 [label="petal width (cm) <= 1.6\ngini = 0.137\nsamples = 27\nvalue = [0, 25, 2]\nclass = versicolor", fillcolor="#49e78b"] ;
2 -> 3 ;
4 [label="gini = 0.0\nsamples = 24\nvalue = [0, 24, 0]\nclass = versicolor", fillcolor="#39e581"] ;
3 -> 4 ;
5 [label="sepal length (cm) <= 5.75\ngini = 0.444\nsamples = 3\nvalue = [0, 1, 2]\nclass = virginica", fillcolor="#c09cf2"] ;
3 -> 5 ;
6 [label="gini = 0.0\n

In [22]:
expected = y_test

In [23]:
predicted = fit.predict(X_test)

In [24]:
conf = metrics.confusion_matrix(expected, predicted)

In [25]:
conf

array([[24,  0,  0],
       [ 0, 24,  0],
       [ 0,  6, 21]], dtype=int64)

In [26]:
DataFrame(conf, index=dataset.target_names, columns=dataset.target_names)

setosa  versicolor  virginica
setosa          24           0          0
versicolor       0          24          0
virginica        0           6         21

In [27]:
metrics.accuracy_score(expected, predicted)

0.92

In [28]:
sum(np.diag(conf)) / sum(sum(conf)) #manual calculation of accuracy score

0.92